apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "esphome.fullname" . }}
  labels:
    {{- include "esphome.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "esphome.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "esphome.selectorLabels" . | nindent 8 }}
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.hostNetwork }}
      hostNetwork: {{ . }}
      {{- end }}
      {{- with .Values.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: esphome
          image: {{ .Values.image.repository }}:{{ include "esphome.imageTag" . }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: ESPHOME_DASHBOARD_USE_POLLING
              value: "true"
          ports:
            - containerPort: 6052
          volumeMounts:
            - name: config
              mountPath: config
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "esphome.fullname" . }}-pvc
