{{- if .Values.machineLearning.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "immich-server.fullname" . }}-ml
  labels:
    {{- include "immich-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: machine-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "immich-ml.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "immich-ml.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.machineLearning.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.machineLearning.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.machineLearning.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: machine-learning
          image: {{ .Values.machineLearning.image.repository }}:{{ .Values.machineLearning.image.tag }}
          {{- with .Values.machineLearning.env }}
          env:
            {{- range $key, $val := . }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: model-cache
              mountPath: /cache
          resources:
            {{- toYaml .Values.machineLearning.resources | nindent 12 }}
      volumes:
        - name: model-cache
          {{- if .Values.machineLearning.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "immich-server.fullname" . }}-ml-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
