apiVersion: v1
kind: Service
metadata:
  name: {{ include "immich-ml.fullname" . }}-svc
  labels:
    {{- include "immich-ml.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 3003 }}
      targetPort: {{ .Values.service.targetPort | default 3003 }}
      {{- if and (eq (.Values.service.type | default "ClusterIP") "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "immich-ml.selectorLabels" . | nindent 4 }}
