apiVersion: v1
kind: ConfigMap
metadata:
  name: dawarich-config
  namespace: {{ .Release.Namespace }}
data:
    DATABASE_NAME: {{ .Values.database.name | quote | default "dawarich_development" }}
    APPLICATION_HOSTS: {{ .Values.ingress.host | quote | default "localhost" }}
    TIME_ZONE: {{ .Values.env.timeZone | quote | default "Europe/Berlin" }}
    APPLICATION_PROTOCOL: {{ .Values.env.APPLICATION_PROTOCOL | quote | default "http" }}
    PROMETHEUS_EXPORTER_ENABLED: {{ .Values.env.PROMETHEUS_EXPORTER_ENABLED | quote | default "false" }}
    PROMETHEUS_EXPORTER_HOST: {{ .Values.env.PROMETHEUS_EXPORTER_HOST | quote | default "0.0.0.0" }}
    PROMETHEUS_EXPORTER_PORT: {{ .Values.env.PROMETHEUS_EXPORTER_PORT | quote | default "9394" }}
    SELF_HOSTED: "true"
    STORE_GEODATA: {{ .Values.env.STORE_GEODATA | quote | default "true" }}
    RAILS_ENV: {{ .Values.env.RAILS_ENV | quote | default "development"}}
    RAILS_APPLICATION_CONFIG_HOSTS: {{ .Values.env.RAILS_APPLICATION_CONFIG_HOSTS | quote | default "dawarich.service7seven.com"}}
    REDIS_URL: {{ .Values.redis.host | quote | default "redis://dawarich_redis:6379" }}
    DATABASE_HOST: {{ .Values.database.host | quote | default "dawarich_db" }}
    DATABASE_USERNAME: {{ .Values.database.username | quote | default "dawarich" }}
    SMTP_SERVER: {{ .Values.smtp.address | quote }}
    SMTP_PORT: {{ .Values.smtp.port | quote }}
    SMTP_DOMAIN: {{ .Values.smtp.domain | quote }}
    SMTP_USERNAME: {{ .Values.smtp.username | quote }}