apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dawarich.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dawarich.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "dawarich.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "dawarich.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
      - name: {{ include "dawarich.fullname" . }}
        image: {{ .Values.image.repository }}:{{ include "dawarich.imageTag" . }}
        stdin: true
        tty: true
        command: ["web-entrypoint.sh"]
        args:
          - "bin/rails"
          - "server"
          - "-p"
          - "{{ .Values.service.targetPort }}"
          - "-b"
          - "::"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          protocol: {{ .Values.service.protocol }}
          name: http
        {{- if .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- else }}
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - >-
                wget -qO - http://127.0.0.1:{{ .Values.service.targetPort }}/api/v1/health | grep -q '"status"\s*:\s*"ok"'
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 30
          initialDelaySeconds: 30
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- else }}
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - >-
                wget -qO - http://127.0.0.1:{{ .Values.service.targetPort }}/api/v1/health | grep -q '"status"\s*:\s*"ok"'
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 30
          initialDelaySeconds: 30
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: SMTP_PASSWORD
          {{- if .Values.smtp.existingSecret.name }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.smtp.existingSecret.name }}
              key: {{ .Values.smtp.existingSecret.key }}
          {{- else }}
          value: {{ .Values.smtp.password | quote }}
          {{- end }}
        - name: DATABASE_PASSWORD
          {{- if .Values.database.existingSecret.name }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.existingSecret.name }}
              key: {{ .Values.database.existingSecret.key }}
          {{- else }}
          value: {{ .Values.database.password | quote }}
          {{- end }}
        {{- if .Values.metrics.serviceMonitor.credentialsSecret }}
        - name: METRICS_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.metrics.serviceMonitor.credentialsSecret }}
              key: metrics-username
        - name: METRICS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.metrics.serviceMonitor.credentialsSecret }}
              key: metrics-password
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "dawarich.fullname" . }}-config
        volumeMounts:
          - name: dawarich-public
            mountPath: /var/app/public
          - name: dawarich-watched
            mountPath: /var/app/tmp/imports/watched
          - name: dawarich-storage
            mountPath: /var/app/storage
          - name: dawarich-db-data
            mountPath: /dawarich_db_data

      - name: {{ include "dawarich.fullname" . }}-sidekiq
        image: {{ .Values.image.repository }}:{{ include "dawarich.imageTag" . }}
        stdin: true
        tty: true
        command: ["sidekiq-entrypoint.sh"]
        args:
          - "sidekiq"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - pgrep -f sidekiq
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 30
          initialDelaySeconds: 30
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - pgrep -f sidekiq
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 30
          initialDelaySeconds: 30
        env:
        - name: RAILS_ENV
          value: {{ .Values.env.RAILS_ENV | quote }}
        - name: REDIS_URL
          value: {{ .Values.redis.host | quote }}
        - name: DATABASE_HOST
          value: {{ .Values.database.host | quote }}
        - name: DATABASE_USERNAME
          value: {{ .Values.database.username | quote }}
        - name: DATABASE_PASSWORD
          {{- if .Values.database.existingSecret.name }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.existingSecret.name }}
              key: {{ .Values.database.existingSecret.key }}
          {{- else }}
          value: {{ .Values.database.password | quote }}
          {{- end }}
        - name: DATABASE_NAME
          value: {{ .Values.database.name | quote }}
        - name: APPLICATION_HOSTS
          value: {{ .Values.ingress.host | quote }}
        - name: TIME_ZONE
          value: {{ .Values.env.timeZone | default "UTC" | quote }}
        - name: APPLICATION_PROTOCOL
          value: {{ .Values.env.APPLICATION_PROTOCOL | quote }}
        - name: PROMETHEUS_EXPORTER_ENABLED
          value: {{ .Values.env.PROMETHEUS_EXPORTER_ENABLED | quote }}
        - name: PROMETHEUS_EXPORTER_PORT
          value: {{ .Values.env.PROMETHEUS_EXPORTER_PORT | quote }}
        - name: SELF_HOSTED
          value: "true"
        - name: STORE_GEODATA
          value: {{ .Values.env.STORE_GEODATA | quote }}
        volumeMounts:
          - name: dawarich-public
            mountPath: /var/app/public
          - name: dawarich-watched
            mountPath: /var/app/tmp/imports/watched
          - name: dawarich-storage
            mountPath: /var/app/storage
      volumes:
        - name: dawarich-public
          persistentVolumeClaim:
            claimName: {{ include "dawarich.fullname" . }}-dawarich-public-pvc
        - name: dawarich-watched
          persistentVolumeClaim:
            claimName: {{ include "dawarich.fullname" . }}-dawarich-watched-pvc
        - name: dawarich-storage
          persistentVolumeClaim:
            claimName: {{ include "dawarich.fullname" . }}-dawarich-storage-pvc
        - name: dawarich-db-data
          persistentVolumeClaim:
            claimName: {{ include "dawarich.fullname" . }}-dawarich-db-data-pvc
