{{- if and (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "dawarich.fullname" . }}-metrics
  namespace: {{ default .Release.Namespace .Values.metrics.serviceMonitor.namespace | quote }}
  labels:
    {{- include "dawarich.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.selector }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "dawarich.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      {{- with .Values.metrics.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      honorLabels: {{ .Values.metrics.serviceMonitor.honorLabels }}
      {{- with .Values.metrics.serviceMonitor.scheme }}
      scheme: {{ . }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.tlsConfig }}
      tlsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.credentialsSecret }}
      basicAuth:
        username:
          name: {{ . }}
          key: metrics-username
        password:
          name: {{ . }}
          key: metrics-password
      {{- end }}
{{- end }}
