apiVersion: v2
name: esphome
version: 0.1.1
appVersion: "2026.7.3"
description: A Helm chart for deploying the ESPHome dashboard on Kubernetes
keywords:
  - esphome
  - home-assistant
  - espressif
  - iot
sources:
  - https://github.com/esphome/esphome
dependencies: []
