apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "database.fullname" . }}-init
  labels:
    {{- include "database.labels" . | nindent 4 }}
data:
  init.sql: |
    CREATE DATABASE {{ .Values.postgresDatabase }};
    GRANT ALL PRIVILEGES ON DATABASE {{ .Values.postgresDatabase }} TO postgres;
