apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-matter-server.fullname" . }}
  labels:
    {{- include "python-matter-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "python-matter-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "python-matter-server.selectorLabels" . | nindent 8 }}
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        fsGroup: {{ .Values.fsGroup }}
      containers:
        - name: matter-server
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: STORAGE_PATH
              value: {{ .Values.storagePath | quote }}
            {{- if .Values.productionMode }}
            - name: PRODUCTION_MODE
              value: "true"
            {{- end }}
          ports:
            - name: websocket
              containerPort: 5580
          volumeMounts:
            - name: data
              mountPath: {{ .Values.storagePath }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "python-matter-server.fullname" . }}-pvc
